var countries = {
    "PR":"Prishtinë",
    "PZ":"Prizren",
    "GJI":"Gjilan",
    "GJA":"Gjakovë",
    "FE":"Ferizaj",
    "PE":"Pejë",
    "ME":"Mitrovicë",
    "DE":"Deçan",
    "GLL":"Gllogovc",
    "KA":"Kaçanik",
    "DR":"Dragash",
    "IS":"Istog",
    "KL":"Klinë",
    "FK":"Fushë Kosovë",
    "KA":"Kamenicë",
    "LE":"Leposaviq",
    "LI":"Lipjan",
    "NO":"Novobërdë",
    "OB":"Obiliq",
    "RA":"Rahovec",
    "PO":"Podujevë",
    "SK":"Skenderaj",
    "SHTI":"Shtime",
    "SHT":"Shtërpce",
    "SU":"Suharekë",
    "VI":"Viti",
    "VU":"Vushtrri",
    "ZP":"Zubin Potok",
    "ZV":"Zveçan",
    "MA":"Malishevë",
    "JU":"Junik",
    "MU":"Mamushë",
    "RA":"Ranillug",
    "HE":"Hani i Elezit",
    "GR":"Graçanicë",
    "PA":"Partesh",
    "KLL":"Kllokot",
    "UL":"Ulqin*",
    "PSH":"Presheve*",
    "S-ED": "Education",
    "S-AG": "Health",
    "S-HL": "Agriculture",
    "S-CL": "Culture", 
    "S-SP":"Sports",
    "S-PL": "Politics",
    "S-CO": "Construction",
    "S-AR": "Architecture", 
    "S-IT":"Information Technology",
    "S-PB": "Private Business",
    "S-EV": "Environment",
    "S-SO": "Social", 
    "S-EC":"Economics",
    "S-CR": "Corruption",
    "S-UE": "Unemployment",
    "S-RA": "Racism", 
    "S-DC":"Discrimination",
    "S-EM": "Employment",
    "S-VL": "Visa Liberalisation",
    "S-RL": "Religion", 
    "S-PR":"Prostitution",
    "S-VI": "Violence",
    "S-NP": "Nepotism",
    "S-WR": "War", 
    "S-JS":"Justice",
}